Repository jeyook/coffeeeeeeee-backend, pull requests merged in 2024-02, with the labels that each got.

#31 [COF-19] 리뷰 삭제 API 구현
  src/review/dto/create-review.dto.ts
  src/review/review.controller.ts
  src/review/review.service.ts
Labels: 리뷰 요청

#32 [COF-67] 카페거리 카페 목록 조회
  src/cafe/cafe.controller.ts
  src/cafe/cafe.module.ts
  src/cafe/cafe.service.ts
Labels: 리뷰 완료

#38 [COF-73] CI/CD 구성
  .dockerignore
  .github/workflows/cicd.yaml
  .gitignore
  Dockerfile
  src/app.module.ts
  src/cafe/cafe.controller.spec.ts
  src/cafe/cafe.service.spec.ts
  src/section/section.controller.spec.ts
  src/section/section.service.spec.ts
  src/user/user.service.spec.ts
  test/app.e2e-spec.ts
Labels: 리뷰 요청

#35 [COF-43] Swagger decorator 분리
  src/cafe/cafe.controller.ts
  src/cafe/decorator/cafe-swagger-decorator.ts
Labels: 리뷰 요청, 머지 요청

#33 [COF-68] 리뷰 개별 조회 API 구현
  src/review/review.controller.ts
  src/review/review.service.ts
Labels: 머지 요청

#65 [COF 76] createLike API 작성
  src/app.module.ts
  src/entity/like.entity.ts
  src/like/like.controller.spec.ts
  src/like/like.controller.ts
  src/like/like.module.ts
  src/like/like.service.spec.ts
  src/like/like.service.ts
Labels: 리뷰 요청

#64 [COF-61] section swagger생성
  src/section/decorator/section-swagger-decorator.ts
  src/section/section.controller.ts
Labels: 머지 요청

#45 [COF-072] bookmark 삭제 기능
  src/bookmark/bookmark.controller.ts
  src/bookmark/bookmark.service.ts
Labels: 리뷰 요청, 머지 요청

#30 [COF-18] 리뷰 수정 API 구현
  src/review/dto/update-review.dto.ts
  src/review/review.controller.ts
  src/review/review.service.spec.ts
  src/review/review.service.ts
  src/user/dto/user-response.dto.ts
Labels: 리뷰 요청

#73 [COF-110] Review API 문서화
  src/common/dto/page-request.dto.ts
  src/review/decorator/review-api-documentation.ts
  src/review/review.controller.ts
Labels: 머지 요청

#34 [COF-049] 북마크 조회 api 테스트 코드 작성
  src/bookmark/bookmark.controller.spec.ts
  src/bookmark/bookmark.controller.ts
  src/bookmark/bookmark.service.spec.ts
  src/bookmark/bookmark.service.ts
  src/bookmark/dto/bookmark-resposnse.dto.ts
Labels: 리뷰 요청, 머지 요청

#37 [COF-66]Section 조회 testcode 작성
  src/section/dto/section-response.dto.ts
  src/section/section.controller.spec.ts
  src/section/section.service.spec.ts
Labels: 리뷰 완료

#69 [COF-71] docs/auth swagger documentation
  src/auth/auth.controller.ts
  src/auth/decorator/auth-api-documentation.ts
  src/user/user.controller.ts
Labels: 리뷰 완료

#74 [COF-087] Bookmark API 문서화
  src/bookmark/bookmark.controller.ts
  src/bookmark/decorator/bookmark-api-documentation.ts
Labels: 리뷰 완료, 머지 요청
